
cc_library(
  name = "macros",
  hdrs = [
    "macros.h",
  ],
)

cc_test(
  name = "macros_test",
  size = "small",
  srcs = [
    "macros_test.cc",
  ],
  deps = [
    ":macros",
    "@com_google_googletest//:gtest_main",
  ],
)
